---
- hosts: localhost
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
  - debug: var=image_ami
  - include_role:
      name: spawn
    vars:
      az: "{{ aws_az }}"
      prefix: "{{ my_prefix }}"
      image_ami: "{{ image_ami }}"
      instance_type: "{{ instance_type }}"

- hosts: new_host
  gather_facts: false
  tasks:
  - copy:
      content: |
        Host {{ target_hostname }}
          hostname {{ ansible_host }}
          IdentityFile {{ ansible_ssh_private_key_file }}
          User ec2-user
      dest: ~/.ssh/{{ my_prefix }}_{{ target_hostname }}_host_config
    delegate_to: localhost
    when: add_host_in_ssh_config
  - name: Final message with a configuration file
    debug:
      msg: "You can connect to your instance with: ssh -F ~/.ssh/{{ my_prefix }}_{{ target_hostname }}_host_config {{ target_hostname }}"
    when: add_host_in_ssh_config
  - name: Final message with no configuration file
    debug:
      msg: "You can connect to your instance with: ssh -i {{ ansible_ssh_private_key_file }} ec2-user@{{ ansible_host }}"
    when: not add_host_in_ssh_config
