---
- hosts: localhost
  gather_facts: false
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
  - include_role:
      name: spawn
    vars:
      az: "{{ aws_az }}"
      prefix: "{{ my_prefix }}"

- hosts: gpu
  gather_facts: false
  tasks:
  - name: Wait until the connection is ready
    ansible.builtin.wait_for_connection:

- hosts: gpu
  become: true
  tasks:
    - include_role:
        name: nvidia.nvidia_driver

- hosts: gpu
  gather_facts: false
  name: Install Ollama
  tasks:
  - name: Wait until the connection is ready
    ansible.builtin.wait_for_connection:
  - shell: |
      curl -fsSL https://ollama.com/install.sh | sh
