- hosts: localhost
  tasks:
    - name: Push the ansible-wisdom-service
      command: rsync -av --delete --filter=':- .gitignore' {{ my_local_ansible_wisdom_model_clone }} gpu:ansible-wisdom-model/

- hosts: gpu
  tasks:
    - name: Install tmux
      package:
        name:
          - tmux
          - vim
          - jq
      become: true
    - name: Prefetch the pytorch image
      command: podman pull docker.io/pytorch/torchserve-nightly:latest-gpu
    - name: Build the image
      command: make model-container
      args:
        chdir: ~/ansible-wisdom-model
    - name: Create the start_server.sh script
      copy:
        content: |
          #!/bin/bash
          #
          set -eux
          wisdom_version=${1}
          port=${2}
          mar="/home/ec2-user/wisdom-ansible-v${wisdom_version}.mar"
          podman stop -i wisdom-v${wisdom_version}
          podman run --gpus all -d --rm -p ${port}:7080 -v ${mar}:/home/model-server/model-store/wisdom.mar --name=wisdom-v${wisdom_version} wisdom
        dest: start_server.sh
        mode: '0755'
    - name: Create the test_server.sh script
      copy:
        content: |
          #!/bin/bash
          set -eux
          port=$1
          curl -X POST http://localhost:${port}/predictions/wisdom -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"instances":[{"context": "", "prompt": "- name: Install PhpRedis extension (Debian)."}]}'|jq .predictions
        dest: test_server.sh
        mode: '0755'
    - name: Start the servers
      command: ./start_server.sh {{ item.version }} {{ item.port }}
      loop: "{{ wisdom_versions  }}"
      loop_control:
        pause: 10
