---
- hosts: localhost
  gather_facts: false
  module_defaults:
    group/aws:
      region: ca-central-1
  tasks:
  - name: Remove the podman connection
    command: podman system connection remove gpu
  - include_role:
      name: spawn
      tasks_from: purge
