- name: Look up the vpc
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": goneri-wisdom-dev-vpc
  register: result
- set_fact:
    vpc: "{{ result.vpcs[0] }}"
- name: Look up the subnet
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc.id }}"
  register: result_subnet


- when: result_subnet.subnets|length > 0
  block:
  - set_fact:
      subnet: "{{ result_subnet.subnets[0] }}"

  - name: Disable the termination protection
    amazon.aws.ec2_instance:
      name: "goneri-wisdom-dev"
      termination_protection: false
      subnet_id: "{{ result_subnet.subnets[0].id }}"

  - name: Delete the instance
    amazon.aws.ec2_instance:
      name: "goneri-wisdom-dev"
      state: absent
      subnet_id: "{{ result_subnet.subnets[0].id }}"
      
  - name: Delete the subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc.id }}"
      cidr: "{{ subnet_cidr }}"
      resource_tags:
        Name: "{{ subnet_name }}"
    register: subnet

      
  - name: Delete the subnet
    ec2_vpc_subnet:
      state: absent
      vpc_id: "{{ vpc.id }}"
      cidr: "{{ subnet_cidr }}"
      resource_tags:
        Name: "{{ subnet_name }}"
    register: subnet


- name: Look up the route table
  amazon.aws.ec2_vpc_route_table_info:
    filters:
      vpc-id: "{{ vpc.id }}"
  register: result
- debug: var=result


- when: result.route_tables|length > 0
  block:
  - debug: var=result.route_tables

  - name: Disassociate gateway from route table
    amazon.aws.ec2_vpc_route_table:
      vpc_id: "{{ vpc.id }}"
      route_table_id: "{{ item.id }}"
      routes: []
      lookup: id
      gateway_id: None
    with_items: "{{ result.route_tables }}"

- name: Delete the security group
  amazon.aws.ec2_group:
    name: "{{ sg_name }}"
    state: absent
  
- name: Delete the Internet gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.id }}"
    state: absent

- name: Info about the VPC
  amazon.aws.ec2_vpc_net_info:
    filters:
      vpc-id: "{{ vpc.id }}"

#- name: Purge the VPC
#  amazon.aws.ec2_vpc_net:
#    vpc_id: "{{ vpc.id }}"
#    state: absent
