---
- name: Install nvidia kernel module
  shell: |
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    subscription-manager config --rhsm.manage_repos=1
    subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms --enable rhel-8-for-x86_64-baseos-rpms --enable rhel-8-for-x86_64-appstream-rpms
    dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
    dnf install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r)
    dnf module install -y nvidia-driver:515-dkms
  args:
    creates: /etc/dbus-1/system.d/nvidia-dbus.conf
  become: true

- name: Enable NVIDIA Container Toolkit repo
  # The URL is hard coded with rhel8.6 because currently (2023-01-06), there is no build for rhel8.7 yet
  shell: |
    dnf config-manager --add-repo https://nvidia.github.io/libnvidia-container/rhel8.6/libnvidia-container.repo
  become: true

- name: Install nvidia-container-toolkit
  package:
    name: nvidia-container-toolkit
  become: true
- name: "nvidia-container-runtime: Turn on no-cgroups"
  ansible.builtin.lineinfile:
    path: /etc/nvidia-container-runtime/config.toml
    regexp: '^#no-cgroups.*'
    line: no-cgroups = true
  become: true

- name: Ensure the nvidia driver is always loaded
  command: systemctl start nvidia-persistenced
  become: true

- name: Run nvidia-smi inside a container without root privilege
  command: podman run --rm --hooks-dir=/usr/share/containers/oci/hooks.d/      docker.io/nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi
  register: result_podman_nvidia_smi
- debug:
    var: result_podman_nvidia_smi
